### ISSUE TITLE
Proxy does not recover after "Stopping listening"

### ISSUE THREAD

**Issue by nh2** [sorintlab/stolon#888]
**What happened**:

There was a temporary Consul downtime in my cluster. After `Stopping listening`, the `stolon-proxy` does not recover:

```
2022-09-11T22:34:54.630Z        INFO        cmd/proxy.go:304        check timeout timer 
2022-09-11T22:34:54.630Z        INFO        cmd/proxy.go:158        Stopping listening
```

No more output for multiple hours, even though Consul evidently recovered (Consul checks on the same machine succeeded).

**What you expected to happen**:

That after `Stopping listening` it eventually starts listening again, as written on https://github.com/sorintlab/stolon/pull/76 it says:

> It will restart listening on successful etcd communication and a populated proxyConf.

**How to reproduce it (as minimally and precisely as possible)**:

Not sure yet, I observed it after a temporary network hickup that temporarily made Consul connections fail.

**Anything else we need to know?**:

**Environment**:
- Stolon version: `0.16.0`
- Stolon running environment (if useful to understand the bug): NixOS Linux

**Comment by nh2** [comment]
I worked around it by simply restarting that `stolon-proxy`, in case that gives a hint.

**Comment by nh2** [comment]
I have a suspicion of what's going on.

Reducing the above goroutine dump to the 3 goroutines that I think are relevant:

```go
goroutine 1 [select, 16591 minutes]:
github.com/sorintlab/stolon/cmd/proxy/cmd.(*ClusterChecker).Start(0xc00003c500, 0x8, 0x0)
        github.com/sorintlab/stolon/cmd/proxy/cmd/proxy.go:338 +0x171
	...

goroutine 7 [select, 16591 minutes]:
github.com/sorintlab/stolon/cmd/proxy/cmd.(*ClusterChecker).TimeoutChecker(0xc00003c500, 0xc000102180)
        github.com/sorintlab/stolon/cmd/proxy/cmd/proxy.go:302 +0xe5
created by github.com/sorintlab/stolon/cmd/proxy/cmd.(*ClusterChecker).Start
        github.com/sorintlab/stolon/cmd/proxy/cmd/proxy.go:335 +0xc5

goroutine 846743 [select, 16591 minutes]:
net/http.(*persistConn).roundTrip(0xc0004446c0, 0xc0000b1200, 0x0, 0x0, 0x0)
        net/http/transport.go:2610 +0x765
net/http.(*Transport).roundTrip(0x2324da0, 0xc0001f0700, 0x30, 0x17188a0, 0x1388)
        net/http/transport.go:592 +0xacb
net/http.(*Transport).RoundTrip(0x2324da0, 0xc0001f0700, 0x2324da0, 0x0, 0x0)
        net/http/roundtrip.go:17 +0x35
net/http.send(0xc0001f0700, 0x1995b60, 0x2324da0, 0x0, 0x0, 0x0, 0xc000010150, 0xf8, 0x1, 0x0)
        net/http/client.go:251 +0x454
net/http.(*Client).send(0x233a680, 0xc0001f0700, 0x0, 0x0, 0x0, 0xc000010150, 0x0, 0x1, 0x1718801)
        net/http/client.go:175 +0xff
net/http.(*Client).do(0x233a680, 0xc0001f0700, 0x0, 0x0, 0x0)
        net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        net/http/client.go:585
github.com/hashicorp/consul/api.(*Client).doRequest(0xc000130a20, 0xc0004abb60, 0xc00046f728, 0xc00004a460, 0x41, 0xc0004abb60)
        github.com/hashicorp/consul/api@v1.4.0/api.go:873 +0xbe
github.com/hashicorp/consul/api.(*KV).getInternal(0xc00046f870, 0xc0001ba941, 0x3a, 0x0, 0x0, 0xc0001ba940, 0x40f71b, 0xc000180000, 0x0)
        github.com/hashicorp/consul/api@v1.4.0/kv.go:131 +0x2b4
github.com/hashicorp/consul/api.(*KV).Get(0xc00046f870, 0xc0001ba941, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/hashicorp/consul/api@v1.4.0/kv.go:65 +0xa5
github.com/docker/libkv/store/consul.(*Consul).getActiveSession(0xc00000e390, 0xc0001ba941, 0x3a, 0x3b, 0x3a, 0x3a, 0x1)
        github.com/docker/libkv@v0.2.1/store/consul/consul.go:159 +0x65
github.com/docker/libkv/store/consul.(*Consul).renewSession(0xc00000e390, 0xc00046f9f0, 0x6fc23ac00, 0xc0001ba941, 0x3a)
        github.com/docker/libkv@v0.2.1/store/consul/consul.go:120 +0x5c
github.com/docker/libkv/store/consul.(*Consul).Put(0xc00000e390, 0xc0001ba8c0, 0x3a, 0xc000102de0, 0x52, 0x60, 0xc000457390, 0xc00046fad0, 0x40fe78)
        github.com/docker/libkv@v0.2.1/store/consul/consul.go:204 +0x136
github.com/sorintlab/stolon/internal/store.(*libKVStore).Put(0xc0000730e0, 0x19c8468, 0xc000040038, 0xc0001ba8c0, 0x3a, 0xc000102de0, 0x52, 0x60, 0xc000457388, 0xc0001c2008, ...)
        github.com/sorintlab/stolon/internal/store/libkv.go:50 +0x90
github.com/sorintlab/stolon/internal/store.(*KVBackedStore).SetProxyInfo(0xc00004c660, 0x19c8468, 0xc000040038, 0xc000235920, 0x6fc23ac00, 0x1, 0x1)
        github.com/sorintlab/stolon/internal/store/kvbacked.go:328 +0x1e4
github.com/sorintlab/stolon/cmd/proxy/cmd.(*ClusterChecker).SetProxyInfo(0xc00003c500, 0x19d89b8, 0xc00004c660, 0x2e, 0x37e11d600, 0x0, 0x0)
        github.com/sorintlab/stolon/cmd/proxy/cmd/proxy.go:183 +0x1d1
github.com/sorintlab/stolon/cmd/proxy/cmd.(*ClusterChecker).Check(0xc00003c500, 0xc0000a3450, 0xc0003dae40)
        github.com/sorintlab/stolon/cmd/proxy/cmd/proxy.go:269 +0x865
github.com/sorintlab/stolon/cmd/proxy/cmd.(*ClusterChecker).Start.func1(0xc0001021e0, 0xc00003c500)
        github.com/sorintlab/stolon/cmd/proxy/cmd/proxy.go:341 +0x2b
created by github.com/sorintlab/stolon/cmd/proxy/cmd.(*ClusterChecker).Start
        github.com/sorintlab/stolon/cmd/proxy/cmd/proxy.go:340 +0x4d5
```

* These three goroutines show, in order:
  1. `ClusterChecker.Start()` is waiting on [its `select`](https://github.com/sorintlab/stolon/blob/4bb4107523c2db09fa711c1d96ddfe33bacf405c/cmd/proxy/cmd/proxy.go#L338)
  2. `ClusterChecker.TimeoutChecker()` is waiting on [its `select`](https://github.com/sorintlab/stolon/blob/4bb4107523c2db09fa711c1d96ddfe33bacf405c/cmd/proxy/cmd/proxy.go#L342)
  3. [`ClusterChecker.Check()`](https://github.com/sorintlab/stolon/blob/4bb4107523c2db09fa711c1d96ddfe33bacf405c/cmd/proxy/cmd/proxy.go#L190) is currently running, stuck in a `Consul.Put()`, called by [`c.SetProxyInfo(c.e, proxy.Generation, proxyTimeout)`](https://github.com/sorintlab/stolon/blob/4bb4107523c2db09fa711c1d96ddfe33bacf405c/cmd/proxy/cmd/proxy.go#L190).
* The next that _should_ happen is that `ClusterChecker.Start()` continues with `case err := <-checkCh:`.
* But this never happens, because `checkCh` never gets written to. This is because the thread [`go func() { checkCh <- c.Check() }()`](https://github.com/sorintlab/stolon/blob/4bb4107523c2db09fa711c1d96ddfe33bacf405c/cmd/proxy/cmd/proxy.go#L340-L342) that was fired off is stuck in `c.Check()`.

The code is written with the assumption that `Check()` will eventually complete; but is permanently stuck.

Thus deadlock.

**Comment by nh2** [comment]
What is the value of `proxyTimeout` is passed to `c.SetProxyInfo(..., proxyTimeout)`?

From

```go
github.com/sorintlab/stolon/internal/store.(*KVBackedStore).SetProxyInfo(0xc00004c660, 0x19c8468, 0xc000040038, 0xc000235920, 0x6fc23ac00, 0x1, 0x1)
github.com/sorintlab/stolon/cmd/proxy/cmd.(*ClusterChecker).SetProxyInfo(0xc00003c500, 0x19d89b8, 0xc00004c660, 0x2e, 0x37e11d600, 0x0, 0x0)
```

I conclude that the value is `0xc00004c660` == `15000000000`, and that's supported by the fact that `KVBackedStore.SetProxyInfo()` has `0x6fc23ac00` which is `30000000000`, which is `2*proxyTimeout`, which is exactly what's done [here](https://github.com/sorintlab/stolon/blob/4bb4107523c2db09fa711c1d96ddfe33bacf405c/cmd/proxy/cmd/proxy.go#L183).

So that means the outer call is `c.SetProxyInfo(..., proxyTimeout = 15 seconds)`.

But it is stuck for `16591 minutes` == `11.5 days`, which is also what I observed from the logs (it's been this long between the `Stopping listening` and the time I took the stack trace).

**Comment by nh2** [comment]
I blieve this issue is already tangentially mentioned in this comment:

https://github.com/sorintlab/stolon/blob/4bb4107523c2db09fa711c1d96ddfe33bacf405c/cmd/proxy/cmd/proxy.go#L331-L335

`if the Check method is blocked somewhere` -- yes.

But as the comment says, the only thing that `TimeoutChecker` achieves is `to forcefully close connection`.
Afterwards, the stolon-proxy will never recover when `Check()` is blocked.

**Comment by nh2** [comment]
PR to work around the issue: https://github.com/sorintlab/stolon/pull/907

**Comment by nh2** [comment]
I managed to reproduce this issue by introducing artificial latency on the VPN network interface over which my consul runs:

```sh
tc qdisc add dev nebula.servers root netem delay 5s

# To remove it afterwards:
tc qdisc del dev nebula.servers root netem
```

After a while this would result in `check timeout timer fired`.
